server:
  port: 8082

spring:
  application:
    name: mcp-neo4j
  ai:
    mcp:
      server:
        protocol: SSE
        name: mcp-neo4j
        version: 1.0.0
        type: sync
        annotation-scanner:
          enabled: true

neo4j:
  uri: neo4j://localhost:7687
  username: neo4j
  password: ai_yunxun
  database: neo4j
