server:
  port: 8081

spring:
  application:
    name: mcp-echart
  ai:
    mcp:
      server:
        protocol: SSE
        name: mcp-echart
        version: 1.0.0
        type: sync
        annotation-scanner:
          enabled: true
