server:
  port: 8081
  application:
      name: mcp-server

spring:
  ai:
    mcp:
      server:
        protocol: SSE
        name: my-mcp-server
        version: 1.0.0
        type: sync
        annotation-scanner:
          enabled: true